version: "3"

services:

  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taromaster
    volumes:
      - ./back/db_data:/var/lib/postgresql/data

  nodeTaromaster:
    container_name: nodeTaromaster
    image: node:19
    restart: always
    working_dir: /home/ubuntu/taromaster
    volumes:
      - ./back:/home/ubuntu/taromaster/
    ports:
      - "3333:3333"
    command: bash -c "npm run prisma db push && node app"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/taromaster


  frontTaromaster:
    container_name: frontTaromaster
    image: node:19
    restart: always
    working_dir: /home/ubuntu/taromaster
    volumes:
      - ./front:/home/ubuntu/taromaster/
    ports:
      - "3000:3000"
    command: bash -c  "npm run build && npm start"
    depends_on:
      - nodeTaromaster
      - db
    environment:
      - REACT_APP_CURRENT_PATH=http://localhost:3000
      - REACT_APP_API=http://localhost:3333

